version: '2'
services:
  mesin1:
    container_name: progjar-mesin-1
    image: royyana/progjar-jupyter:latest
    user: root
    privileged: true
    cap_add:
    - NET_RAW
    - ALL
    - NET_ADMIN
    ports:
      - "60001:8888"
      - "50001:6666"
    environment:
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
      - "GRANT_SUDO=yes"
      - "PASSWORD=mesin1"
    working_dir: /home/jovyan/work
    volumes:
      - ./work1:/home/jovyan/work
    networks:
      default:
        priority: 1
      progjar-network:
        priority: 2
        ipv4_address: "172.16.16.101"
  mesin2:
    container_name: progjar-mesin-2
    image: royyana/progjar-jupyter:latest
    user: root
    privileged: true
    cap_add:
    - NET_RAW
    - ALL
    - NET_ADMIN
    ports:
      - "60002:8888"
      - "50002:6666"
    environment:
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
      - "GRANT_SUDO=yes"
      - "PASSWORD=mesin2"
    working_dir: /home/jovyan/work
    volumes:
      - ./work2:/home/jovyan/work
    networks:
      default:
        priority: 1
      progjar-network:
        priority: 2
        ipv4_address: "172.16.16.102"
  mesin3:
    container_name: progjar-mesin-3
    image: royyana/progjar-jupyter:latest
    user: root
    privileged: true
    cap_add:
    - NET_RAW
    - ALL
    - NET_ADMIN
    ports:
      - "60003:8888"
      - "50003:6666"
    environment:
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
      - "GRANT_SUDO=yes"
      - "PASSWORD=mesin3"
    working_dir: /home/jovyan/work
    volumes:
      - ./work3:/home/jovyan/work
    networks:
      default:
        priority: 1
      progjar-network:
        priority: 2
        ipv4_address: "172.16.16.103"
networks:
  default:
    driver: bridge
  progjar-network:
    name: progjar-network
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.name: "progjar-network"  
    ipam:
      driver: default
      config:
        - subnet: 172.16.16.0/24
          gateway: 172.16.16.1


